apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: kubeflow
spec:
  storageClassName: "nfs-storageclass"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
